version: '3.3'
services:
  mysql:
    build:
      context: /home/tools/bael/dung/B015
      args:
        - MYSQL_DATABASE=itransition_task4
        - MYSQL_USER=rootMuhammad
        - MYSQL_PASSWORD=root
        - MYSQL_ROOT_PASSWORD=root
    ports:
      - "$3306:3306"
