version: '3.9'
services:
  mysql-db:
    container_name: mysql-container
    image: mysql:latest
    build:
        context: .
        dockerfile: Dockerfile
    environment:
        MYSQL_DATABASE: itransition_task4
        MYSQL_USER: muhammad
        MYSQL_PASSWORD: root
        MYSQL_ROOT_PASSWORD: root
    ports:
        - "3306:3306"
    volumes:
        - mysql-data:/var/lib/mysql
volumes:
    mysql-data: